config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
  }
  get '/signup', to: 'users#new'
  get '/about', to: "static_pages#about"
  root 'static_pages#home'
  resources :users, only: [:show, :index]
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/install.rb
class Install < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def remember_me
    true
  end

  def feed
    posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user,   only: :destroy

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :title, :what_content, :what_problem, :question,
                                 :interest, :important, :solution, :start, :end, :different, :most,
                                 :agreement, :chapter, :intersting, :sentence, :heart, :dull,
                                 :difficult, :titles, :foreword, :summary, :picture, :publisher,
                                 :author, :pubdate, :description)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @post = Post.find_by(params[:id])
      @feed_items = current_user.feed.all
    end
  end

  def about
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
    log_out
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all
    if @user.posts.any?
      @post = Post.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user == current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <ul class="logo"><%= link_to "bookrize_app", root_path, id: "logo" %></ul>
    <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "home", root_path %></li>
      <li><%= link_to "about", about_path %></li>
      <% if user_signed_in? %>
      <li class="dropdown">
        <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" aria-haspopup="true" aria-expanded="false">My page <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "プロフィール", current_user %></li>
          <li><%= link_to "編集", edit_user_registration_path(@user) %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "You sure?" } %></li>
        </ul>
      </li>
      <li><%= link_to "Bookrize", new_post_path %><li>
      <% else %>
      <li><%= link_to "log_in", new_user_session_path %></li>
      <% end %>
    </ul>
    <nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>
      - bookrize_app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=BioRhyme+Expanded" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="background">
      <div class="main-containers">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <%= yield %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= @post.id %>">
<span class="user">投稿者　<%= post.user.name %></span>
<span class="content"><%= link_to post.title, post_path(post), :style=>"color:lightblue;" %></span>
<span >
  Posted <%= time_ago_in_words(post.created_at) %> ago.
</span>
<% if current_user?(post.user) %>
  <%= link_to "編集", edit_post_path(post), :style=>"color:lightblue;" %>
  <%= link_to "削除", post, method: :delete, :style=>"color:lightblue;",
    data: { confirm: '削除しますか？' }%>
<% end %>
</li>

app/views/posts/edit.html.erb
<% provide(:title, "edit") %>
<%= form_for(@post) do |f| %>

<h4>・読書前に入力</h4>

<%= render 'shared/book_edit' %>

<div class="field">
  <%= f.label :この本を読むことがなぜ重要なのか %><br />
  <%= f.text_area :important, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :この本から学びたい興味あると思うことを３つ %><br />
  <%= f.text_area :interest, :size=>"60x3" %>
</div>

<div class="field">
  <%= f.label :章ごとに質問化して答えを予測 %><br />
  <%= f.text_area :question, :size=>"60x10" %>
</div>

<div class="field">
  <%= f.label :章ごとの役割、論理構造を予測 %><br />
  <%= f.text_area :what_content, :size=>"60x10" %>
</div>

<h4>・読書中に入力</h4>

<div class="field">
  <%= f.label :章ごとの疑問に答ていく %><br />
  <%= f.text_area :chapter, :size=>"60x10" %>
</div>

<h4>・読書後に入力</h4>

<div class="field">
  <%= f.label :翌日に章ごとに要約 %><br />
  <%= f.text_area :summary, :size=>"60x10" %>
</div>

<div class="field">
  <%= f.label :"この本の問題意識(メインテーマ)は何か" %><br />
  <%= f.text_area :what_problem, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :それを解決する方法は何か %><br />
  <%= f.text_area :solution, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :どのように始まったか %><br />
  <%= f.text_area :start, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :どのように終わったか %><br />
  <%= f.text_area :end, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :他の本とどこが違うか %><br />
  <%= f.text_area :different, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :作者が一番伝えたいことは何かなぜそれが重要なのか %><br />
  <%= f.text_area :most, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :作者のどこに一番賛同できるかその理由は何か %><br />
  <%= f.text_area :agreement, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :面白かった事例は何か %><br />
  <%= f.text_area :intersting, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :この本の一番大事な一文はどこかその理由は %><br />
  <%= f.text_area :sentence, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :一番心に刺さったのはどこか %><br />
  <%= f.text_area :heart, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :どこかがつまらなかったか%><br />
  <%= f.text_area :dull, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :どこがわかりづらかったか %><br />
  <%= f.text_area :difficult, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :タイトルは適切かもっと良いタイトルは何か %><br />
  <%= f.text_area :titles, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :前書きは役に立ったか改善点はないか %><br />
  <%= f.text_area :foreword, :size=>"60" %>
</div>

<div class="field">
  <%= f.label :予測していた論理構造が合っていたか %><br />
  <%= f.text_area :content, placeholder: "this is last question...", :size=>"60" %>
</div>

<div class="actions">
<%= f.submit "投稿", class: "btn btn-primary" %>
</div>

<% end %>

app/views/posts/index.html.erb
<h4>投稿一覧</h4>
<% @posts.each do |post| %>
  <h5>
    <%= link_to post.user.name, post.user, :style=>"color: pink;" %>
    <%= link_to post.title, post, :style=>"color: pink;" %>
  </h5>
<% end %>

app/views/posts/new.html.erb
<% provide(:title, "post") %>
<h2><%= link_to "お手本を見る", post_path(1), :style=>"color: pink;" %></h2>
<%= form_for(@post) do |f| %>

  <h4>・読書前に入力</h4>
  <%= render 'shared/book' %>

  <div class="field">
    <%= f.label :この本を読むことがなぜ重要なのか %><br />
    <%= f.text_area :important, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :この本から学びたい興味あると思うことを３つ %><br />
    <%= f.text_area :interest, :size=>"60x3" %>
  </div>

  <div class="field">
    <%= f.label :章ごとに質問化して答えを予測 %><br />
    <%= f.text_area :question, :size=>"60x10" %>
  </div>

  <div class="field">
    <%= f.label :章ごとの役割、論理構造を予測 %><br />
    <%= f.text_area :what_content, :size=>"60x10" %>
  </div>

  <h4>・読書中に入力</h4>

  <div class="field">
    <%= f.label :章ごとの疑問に答ていく %><br />
    <%= f.text_area :chapter, :size=>"60x10" %>
  </div>

  <h4>・読書後に入力</h4>

  <div class="field">
    <%= f.label :翌日に章ごとに要約 %><br />
    <%= f.text_area :summary, :size=>"60x10" %>
  </div>

  <div class="field">
    <%= f.label :"この本の問題意識(メインテーマ)は何か" %><br />
    <%= f.text_area :what_problem, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :それを解決する方法は何か %><br />
    <%= f.text_area :solution, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :どのように始まったか %><br />
    <%= f.text_area :start, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :どのように終わったか %><br />
    <%= f.text_area :end, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :他の本とどこが違うか %><br />
    <%= f.text_area :different, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :作者が一番伝えたいことは何かなぜそれが重要なのか %><br />
    <%= f.text_area :most, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :作者のどこに一番賛同できるかその理由は何か %><br />
    <%= f.text_area :agreement, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :面白かった事例は何か %><br />
    <%= f.text_area :intersting, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :この本の一番大事な一文はどこかその理由は %><br />
    <%= f.text_area :sentence, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :一番心に刺さったのはどこか %><br />
    <%= f.text_area :heart, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :どこかがつまらなかったか%><br />
    <%= f.text_area :dull, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :どこがわかりづらかったか %><br />
    <%= f.text_area :difficult, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :タイトルは適切かもっと良いタイトルは何か %><br />
    <%= f.text_area :titles, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :前書きは役に立ったか改善点はないか %><br />
    <%= f.text_area :foreword, :size=>"60" %>
  </div>

  <div class="field">
    <%= f.label :予測していた論理構造が合っていたか %><br />
    <%= f.text_area :content, placeholder: "this is last question...", :size=>"60" %>
  </div>

  <div class="actions">
    <%= f.submit "投稿", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/posts/show.html.erb
<% provide(:title, "post") %>
<h4>本の概要</h4>
<h5>タイトル</h5>
<p class = "item"><%= @post.title %></p>
<h5>出版社</h5>
<p class = "item"><%= @post.publisher %></p>
<h5>著者</h5>
<p class = "item"><%= @post.author %></p>
<h5>出版日</h5>
<p class = "item"><%= @post.pubdate %></p>
<h5>内容説明</h5>
<p class = "item"><%= simple_format(@post.description) %></p>
<h4>この本を読むことがなぜ重要なのか</h4>
<p class = "item"><%= simple_format(@post.important) %></p>
<h4>この本から学びたい興味あると思うことを３つ</h4>
<p class = "item"><%= simple_format(@post.interest) %></p>
<h4>質問化した章と予測した答え</h4>
<p class = "item"><%= simple_format(@post.question) %></p>
<h4>予測した章ごとの役割、論理構造</h4>
<p class = "item"><%=simple_format(@post.what_content) %></p>
<h4>章ごとの疑問の答え</h4>
<p class = "item"><%= simple_format(@post.chapter) %></p>
<h4>章ごとの要約</h4>
<p class = "item"><%= simple_format(@post.summary) %></p>
<h4>:この本の問題意識(メインテーマ)は何か</h4>
<p class = "item"><%= simple_format(@post.what_problem) %></p>
<h4>"それを解決する方法は何か"</h4>
<p class = "item"><%= simple_format(@post.solution) %></p>
<h4>どのように始まったか</h4>
<p class = "item"><%= simple_format(@post.start) %></p>
<h4>どのように終わったか</h4>
<p class = "item"><%= simple_format(@post.end) %></p>
<h4>他の本とどこが違うか</h4>
<p class = "item"><%= simple_format(@post.different) %></p>
<h4>作者が一番伝えたいことは何かなぜそれが重要なのか</h4>
<p class = "item"><%= simple_format(@post.most) %></p>
<h4>作者のどこに一番賛同できるかその理由は何か</h4>
<p class = "item"><%= simple_format(@post.agreement) %></p>
<h4>面白かった事例は何か</h4>
<p class = "item"><%= simple_format(@post.intersting) %></p>
<h4>この本の一番大事な一文はどこかその理由は</h4>
<p class = "item"><%= simple_format(@post.sentence) %></p>
<h4>一番心に刺さったのはどこか</h4>
<p class = "item"><%= simple_format(@post.heart) %></p>
<h4>どこかがつまらなかったか</h4>
<p class = "item"><%= simple_format(@post.dull) %></p>
<h4>どこがわかりづらかったか</h4>
<p class = "item"><%= simple_format(@post.difficult) %></p>
<h4>タイトルは適切かもっと良いタイトルは何か</h4>
<p class = "item"><%= simple_format(@post.titles) %></p>
<h4>前書きは役に立ったか改善点はないか</h4>
<p class = "item"><%= simple_format(@post.foreword) %></p>
<h4>予測していた論理構造が合っていたか</h4>
<p class = "item"><%= simple_format(@post.content) %></p>

app/views/shared/_book.html.erb
<h5>↓を入力すると上５つの項目が自動で入力されます</h5>
<div class="field">
  ISBN13：<input id="isbn" type="text" name="isbn" value="" autofocus>
  <button id="getBookInfo" class="btn btn-default">書籍情報取得</button>
</div>

<div class="field">
  <p id="thumbnail"></p>
</div>

<div class="field">
  書籍名 <br /><input id="title" type="text" name=post[title] value="" size=60 >
</div>

<div class="field">
  出版社<br /><input id="publisher" type="text" name=post[publisher] value="" size=60 >
</div>

<div class="field">
  著者<br /><input id="author" type="text" name=post[author] value="" size=60 >
</div>

<div class="field">
  出版日<br /><input id="pubdate" type="text"  name=post[pubdate] value="" size=60>
</div>

<div class="field">
  詳細<br /><textarea id="description" type="text" name=post[description] value="" rows="4" cols="60" ></textarea>
</div>

<script>
  $(function() {
    $('#getBookInfo').click( function( e ) {
      e.preventDefault();
        const isbn = $("#isbn").val();
          const url = "https://api.openbd.jp/v1/get?isbn=" + isbn;

            $.getJSON( url, function( data ) {
              if( data[0] == null ) {
                alert("データが見つかりません");
              } else {
                if( data[0].summary.cover == "" ){
                  $("#thumbnail").html('<img src=\"\" />');
                } else {
                  $("#thumbnail").html('<img src=\"' + data[0].summary.cover + '\" style=\"border:solid 1px #000000\" />');
                  }
                    $("#title").val(data[0].summary.title);
                    $("#publisher").val(data[0].summary.publisher);
                    $("#author").val(data[0].summary.author);
                    $("#pubdate").val(data[0].summary.pubdate);
                    $("#description").val(data[0].onix.CollateralDetail.TextContent[0].Text);
                }
            });
        });
    });
</script>

app/views/shared/_book_edit.html.erb
<div>
  <a id="thumbnail" type="hidden" name=post[picture] html=""></a>
</div>

<div class="field">
  書籍名 <br /><input id="title" type="text" name=post[title] size=60 value=<%= @post.title %> >
</div>

<div class="field">
  出版社<br /><input id="publisher" type="text" name=post[publisher] size=60 value=<%= @post.publisher %> >
</div>

<div class="field">
  著者<br /><input id="author" type="text" name=post[author] size=60 value=<%= @post.author %> >
</div>

<div class="field">
  出版日<br /><input id="pubdate" type="text"  name=post[pubdate] size=60 value=<%= @post.pubdate %> >
</div>

<div class="field">
  詳細<br /><textarea id="description" type="text" name=post[description] rows="4" cols="60" ><%= @post.description %></textarea>
</div>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <h5><%= render @feed_items %></h5>
  </ol>
<% end %>

app/views/static_pages/_defult_home.html.erb
<div class="center">
  <h1>Bookrizeへようこそ！</h1>
  <h2>さっそく登録してみよう！</h2>
  <%= link_to "登録", new_user_registration_path, class: "btn btn-lg btn-primary"%>
  <p>すでに登録済みですか？<?p><br />
  <%= link_to "ログイン", new_user_session_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="center">
  <p>Bookrizeとは読んだ本を記憶に残すためのアプリです。</p>
  <p>ログインして早速使ってみよう！</p>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "about") %>
<div>
  <h2>Bookrizeの使い方</h2>
  <h3>使い方は簡単！</h3>
  <h3>ログインして”投稿(bookrize)”ページから、読んだ本の内容を登録するだけです。</h3>
</div>
<br />
<div>
   <h2>科学的にわかっている読書の効果</h2>
   <ul class="center">
     <li>年収が上がる</li>
     <li>創造力が上がる</li>
     <li>対人能力が上がる</li>
     <li>言語能力が高くなる</li>
     <li>学校の成績が良くなる</li>
     <li>問題解決能力が高くなる</li>
     <li>ストレスを軽減してくれる</li>
   </ul>
</div>
<br />
<div>
   <h3>しかし！いくら本を読んでも頭に残すことができなければ無意味です！</h3>
   <h3>けれども、忘れないように本の内容をノートにまとめても、やはり忘れてしまいます。</h3>
   <h3>そこで、ハーバード大の心理学者やチャールストン大の哲学者など著名な科学者の考えを元に</h3>
   <h3>絶対に内容を忘れなくする為の書評サイトを作りました。</h3>
</div>
 <br />
<div>
   <h3>BookrizeとはBook(本)とMemorize(記憶する)を組み合わせた造語です。</h3>
   <h3>早速本を読んで記憶に残そう！</h3>
   <% unless user_signed_in? %>
   <%= link_to "登録", new_user_registration_path, class: "btn btn-lg btn-primary"%>
   <% end %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title,"home") %>
<% if user_signed_in? %>
  <h3>Time Line</h3>
    <%= render 'shared/feed' %>
    <%= link_to "投稿一覧", posts_path, :style=>"color: pink;" %>
<% else %>
  <%= render 'defult_home' %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "My_page") %>
<% if current_user?(@user) %>
  <h1>マイページ（<%= @user.name %>）</h1>
  <%= link_to "登録情報を変更する", edit_user_registration_path(@user), :style=>"color:lightblue;" %>
  <section class="post_form">
    <%= link_to "投稿する", new_post_path, class: "btn btn-lg btn-primary"  %>
  </section>
<% else %>
  <h1>ユーザーページ（<%= @user.name %>）</h1>
<% end %>
<% if @user.posts.any? %>
  <h3>投稿一覧 (<%= @user.posts.count %>)</h3>
  <ol class="posts">
  <%= render @posts %>
  </ol>
<% end %>